### ISSUE TITLE
Ignored auth_protocol results NTLM_USER_FILE error

### ISSUE THREAD

**Issue by Bargenish** [jborean93/smbprotocol#109]
Hi, Im encountering an issue when trying to authenticate a remote server.
I'm using the High level API and have the following configured:
* for the register_session:
```python
register_session(
            server=hostname,
            username=user,
            password=password,
            port=445,
            encrypt=encrypt,
            auth_protocol='ntlm')
```

* client config:
```python
smbclient.ClientConfig(username=user, password=password, require_secure_negotiate=verify, domain_controller=dc)
```
where the username, password, and all other variables were verified and correct. 

*The issue*:
Even though the auth_protocol was set to `ntlm` the request first attempts to use negotiate and then falls back to ntlm (we do not support Kerberos at the moment).
The problem with it is that the username field is not being passed to the ntlm request and then fails on 

**Logs**
```
[smbprotocol.connection] - Negotiated dialect: (785) SMB_3_1_1
 python logging: INFO [smbprotocol.connection] - Connection require signing: True
 python logging: INFO [smbprotocol.session] - Initialising session with username: None
 python logging: DEBUG [smbprotocol.session] - Decoding SPNEGO token containing supported auth mechanisms
 python logging: DEBUG [spnego.negotiate] - SPNEGO step input: YHYGBisGAQUFAqBsMGqgPDA6BgorBgEEAYI3AgIeBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKoZIhvcSAQICAwYKKwYBBAGCNwICCqMqMCigJhskbm90X2RlZmluZWRfaW5fUkZDNDE3OEBwbGVhc2VfaWdub3Jl
 python logging: DEBUG [spnego.negotiate] - Failed to create gssapi context for SPNEGO protocol ntlm: SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath
Exception message is [Traceback (most recent call last):
   File "/usr/local/lib/python3.9/site-packages/smbprotocol/session.py", line 275, in connect
    out_token = context.step(in_token)
   File "/usr/local/lib/python3.9/site-packages/spnego/negotiate.py", line 119, in step
    mech_token_in, mech_list_mic, is_spnego = self._step_spnego_input(in_token=in_token)
   File "/usr/local/lib/python3.9/site-packages/spnego/negotiate.py", line 159, in _step_spnego_input
    mech_list = self._rebuild_context_list(mech_types=in_token.mech_types)
   File "/usr/local/lib/python3.9/site-packages/spnego/negotiate.py", line 374, in _rebuild_context_list
    raise BadMechanismError(context_msg="Unable to negotiate common mechanism", base_error=last_err)
 spnego.exceptions.BadMechanismError: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism
```
Good to know:
- We have NTLM and LM disabled on our server but NTLMv2 enabled.
- We are using the latest version of the smbprotocol package (1.5.1)

Thanks.

**Comment by jborean93** [comment]
What I am finding confusing is that both the `uth_protocol` and `username/password` settings are being ignored. The log indicates that the auth being used in Negotiate auth without any username and/or password being set which goes against what your `ClientConfig` is set as. Is `username=user, password=password` actually set to any value other than `None` at that point.

Can you wrap all your code with the following to see the full stack trace. I would like to see what code is actually creating the session and potentially why it's not populating the proper values.

```python
import traceback

try:
    my_code()
except Exception, err:
    traceback.print_exc()
```

**Comment by Bargenish** [comment]
@jborean93  thanks for responding.
full traceback:
```
Error: [Traceback (most recent call last):
   
   File "<string>", line 230, in <module>
   File "<string>", line 196, in main
   File "/usr/local/lib/python3.9/site-packages/smbclient/_pool.py", line 58, in __call__
    cls.__instances[cls] = super(_ConfigSingleton, cls).__call__(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/smbclient/_pool.py", line 105, in __init__
    self.domain_controller = domain_controller
   File "/usr/local/lib/python3.9/site-packages/smbclient/_pool.py", line 123, in domain_controller
    ipc_tree = get_smb_tree(u'\\\\%!s(MISSING)\\IPC$' %!v(MISSING)alue)[0]
   File "/usr/local/lib/python3.9/site-packages/smbclient/_pool.py", line 293, in get_smb_tree
    session = register_session(server, username=username, password=password, port=port, encrypt=encrypt,
   File "/usr/local/lib/python3.9/site-packages/smbclient/_pool.py", line 360, in register_session
    session.connect()
   File "/usr/local/lib/python3.9/site-packages/smbprotocol/session.py", line 277, in connect
    raise SMBAuthenticationError("Failed to authenticate with server: %!s(MISSING)" %!s(MISSING)tr(err.message))
 smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism
] (2604)'] 
```


python logging:
```
python logging: DEBUG [spnego.gss] - Python gssapi not available, cannot use any GSSAPIProxy protocols: No module named 'gssapi' 
python logging: DEBUG [spnego.gss] - Python gssapi IOV extension not available: No module named 'gssapi' 
python logging: DEBUG [spnego.sspi] - SSPI bindings not available, cannot use any SSPIProxy protocols: No module named 'spnego._sspi_raw.sspi' 
python logging: INFO [smbprotocol.connection] - Initialising connection, guid: e27784b2-d35c-4450-9023-ede3dd76b1ea, require_signing: True, server_name: ldap.bessemer.com, port: 445 
python logging: INFO [smbprotocol.connection] - Setting up transport connection 
python logging: INFO [smbprotocol.transport] - Connecting to DirectTcp socket 
python logging: DEBUG [smbprotocol.transport] - Socket recv(4) (total 4) 
python logging: INFO [smbprotocol.connection] - Starting negotiation with SMB server
python logging: INFO [smbprotocol.connection] - Negotiating with SMB2 protocol with highest client dialect of: SMB_3_1_1 
python logging: DEBUG [smbprotocol.connection] - Adding client guid e27784b2-d35c-4450-9023-ede3dd76b1ea to negotiate request 
python logging: DEBUG [smbprotocol.connection] - Adding client capabilities 69 to negotiate request
python logging: DEBUG [smbprotocol.connection] - Adding preauth integrity capabilities of hash SHA512 and salt b'ou3v\r\xeeI\n\xdf.\xd5+>\xd8t\x1f\x99}\xf0\xdd\xaf\xed\xa0@{w\x04\xf0S\xfe$\x9e' to negotiate request 
python logging: DEBUG [smbprotocol.connection] - Adding encryption capabilities of AES128 GCM and AES128 CCM to negotiate request 
python logging: INFO [smbprotocol.connection] - Sending SMB2 Negotiate message
python logging: DEBUG [smbprotocol.connection] - SMB3NegotiateRequest:
    structure_size = 36
    dialect_count = 5
    security_mode = (2) SMB2_NEGOTIATE_SIGNING_REQUIRED
    reserved = 0
    capabilities = (69) SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_ENCRYPTION, SMB2_GLOBAL_CAP_LARGE_MTU
    client_guid = e27784b2-d35c-4450-9023-ede3dd76b1ea
    negotiate_context_offset = 112
    negotiate_context_count = 2
    reserved2 = 0
    dialects = [
        (514) SMB_2_0_2,
        (528) SMB_2_1_0,
        (768) SMB_3_0_0,
        (770) SMB_3_0_2,
        (785) SMB_3_1_1
    ]
    padding = 00 00
    negotiate_context_list = [
        SMB2NegotiateContextRequest:
            context_type = (1) SMB2_PREAUTH_INTEGRITY_CAPABILITIES
            data_length = 38
            reserved = 0
            data =
            SMB2PreauthIntegrityCapabilities:
                hash_algorithm_count = 1
                salt_length = 32
                hash_algorithms = [
                    (1) SHA_512
                ]
                salt = 6F 75 33 76 0D EE 49 0A DF 2E D5 2B 3E D8 74 1F 99 7D F0 DD AF ED A0 40 7B 77 04 F0 53 FE 24 9E

                Raw Hex:
                    01 00 20 00 01 00 6F 75
                    33 76 0D EE 49 0A DF 2E
                    D5 2B 3E D8 74 1F 99 7D
                    F0 DD AF ED A0 40 7B 77
                    04 F0 53 FE 24 9E
            padding = 00 00

            Raw Hex:
                01 00 26 00 00 00 00 00
                01 00 20 00 01 00 6F 75
                33 76 0D EE 49 0A DF 2E
                D5 2B 3E D8 74 1F 99 7D
                F0 DD AF ED A0 40 7B 77
                04 F0 53 FE 24 9E 00 00,
        SMB2NegotiateContextRequest:
            context_type = (2) SMB2_ENCRYPTION_CAPABILITIES
            data_length = 6
            reserved = 0
            data =
            SMB2EncryptionCapabilities:
                cipher_count = 2
                ciphers = [
                    (2) AES_128_GCM,
                    (1) AES_128_CCM
                ]

                Raw Hex:
                    02 00 02 00 01 00
            padding = 

            Raw Hex:
                02 00 06 00 00 00 00 00
                02 00 02 00 01 00
    ]

    Raw Hex:
        24 00 05 00 02 00 00 00
        45 00 00 00 E2 77 84 B2
        D3 5C 44 50 90 23 ED E3
        DD 76 B1 EA 70 00 00 00
        02 00 00 00 02 02 10 02
        00 03 02 03 11 03 00 00
        01 00 26 00 00 00 00 00
        01 00 20 00 01 00 6F 75
        33 76 0D EE 49 0A DF 2E
        D5 2B 3E D8 74 1F 99 7D
        F0 DD AF ED A0 40 7B 77
        04 F0 53 FE 24 9E 00 00
        02 00 06 00 00 00 00 00
        02 00 02 00 01 00

python logging: DEBUG [smbprotocol.transport] - Socket recv() returned 4 bytes (total 4) 
python logging: DEBUG [smbprotocol.transport] - Socket recv(308) (total 308)
python logging: DEBUG [smbprotocol.transport] - Socket recv() returned 308 bytes (total 308)
ython logging: DEBUG [smbprotocol.transport] - Socket recv(4) (total 4) 
python logging: INFO [smbprotocol.connection] - Receiving SMB2 Negotiate response 
python logging: DEBUG [smbprotocol.connection] - SMB2HeaderResponse:
    protocol_id = FE 53 4D 42
    structure_size = 64
    credit_charge = 0
    status = (0) STATUS_SUCCESS
    command = (0) SMB2_NEGOTIATE
    credit_response = 1
    flags = (1) SMB2_FLAGS_SERVER_TO_REDIR
    next_command = 0
    message_id = 0
    reserved = 0
    tree_id = 0
    session_id = 0
    signature = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    data = 41 00 01 00 11 03 02 00 D6 24 97 CB EF 11 5B 4F 82 0A F2 2E 56 21 9E 2F 07 00 00 00 00 00 80 00 00 00 80 00 00 00 80 00 A7 3A 54 EB F1 56 D7 01 00 DC 71 79 12 55 D7 01 80 00 78 00 F8 00 00 00 60 76 06 06 2B 06 01 05 05 02 A0 6C 30 6A A0 3C 30 3A 06 0A 2B 06 01 04 01 82 37 02 02 1E 06 09 2A 86 48 82 F7 12 01 02 02 06 09 2A 86 48 86 F7 12 01 02 02 06 0A 2A 86 48 86 F7 12 01 02 02 03 06 0A 2B 06 01 04 01 82 37 02 02 0A A3 2A 30 28 A0 26 1B 24 6E 6F 74 5F 64 65 66 69 6E 65 64 5F 69 6E 5F 52 46 43 34 31 37 38 40 70 6C 65 61 73 65 5F 69 67 6E 6F 72 65 01 00 26 00 00 00 00 00 01 00 20 00 01 00 B5 20 FF 09 A0 DA FB FD EC B1 AE 9E 37 12 AD 60 A7 50 76 78 BD BD 86 61 B2 80 D7 DF 4A 9A B7 C4 00 00 02 00 04 00 00 00 00 00 01 00 02 00

    Raw Hex:
        FE 53 4D 42 40 00 00 00
        00 00 00 00 00 00 01 00
        01 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        41 00 01 00 11 03 02 00
        D6 24 97 CB EF 11 5B 4F
        82 0A F2 2E 56 21 9E 2F
        07 00 00 00 00 00 80 00
        00 00 80 00 00 00 80 00
        A7 3A 54 EB F1 56 D7 01
        00 DC 71 79 12 55 D7 01
        80 00 78 00 F8 00 00 00
        60 76 06 06 2B 06 01 05
        05 02 A0 6C 30 6A A0 3C
        30 3A 06 0A 2B 06 01 04
        01 82 37 02 02 1E 06 09
        2A 86 48 82 F7 12 01 02
        02 06 09 2A 86 48 86 F7
        12 01 02 02 06 0A 2A 86
        48 86 F7 12 01 02 02 03
        06 0A 2B 06 01 04 01 82
        37 02 02 0A A3 2A 30 28
        A0 26 1B 24 6E 6F 74 5F
        64 65 66 69 6E 65 64 5F
        69 6E 5F 52 46 43 34 31
        37 38 40 70 6C 65 61 73
        65 5F 69 67 6E 6F 72 65
        01 00 26 00 00 00 00 00
        01 00 20 00 01 00 B5 20
        FF 09 A0 DA FB FD EC B1
        AE 9E 37 12 AD 60 A7 50
        76 78 BD BD 86 61 B2 80
        D7 DF 4A 9A B7 C4 00 00
        02 00 04 00 00 00 00 00
        01 00 02 00 
python logging: INFO [smbprotocol.connection] - Negotiated dialect: (785) SMB_3_1_1
python logging: INFO [smbprotocol.connection] - Connection require signing: True 
python logging: INFO [smbprotocol.session] - Initialising session with username: None 
python logging: DEBUG [smbprotocol.session] - Decoding SPNEGO token containing supported auth mechanisms 
python logging: DEBUG [spnego.negotiate] - SPNEGO step input: YHYGBisGAQUFAqBsMGqgPDA6BgorBgEEAYI3AgIeBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKoZIhvcSAQICAwYKKwYBBAGCNwICCqMqMCigJhskbm90X2RlZmluZWRfaW5fUkZDNDE3OEBwbGVhc2VfaWdub3Jl 
python logging: DEBUG [spnego.negotiate] - Failed to create gssapi context for SPNEGO protocol ntlm: SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath 

```

**Comment by Bargenish** [comment]
@jborean93 Hi,
Did you have the chance to look at the logs?

**Comment by jborean93** [comment]
Scratch that I think I know why. We set `domain_controller` last but the `__init__` method is still running so when the setter for `domain_controller` goes to [get_smb_tree](https://github.com/jborean93/smbprotocol/blob/master/smbclient/_pool.py#L123) the config hasn't been stored in the singleton and thus won't have the username and password set. I'll have to create a PR to fix this but for the time being you can do the following to workaround it


```python
config = smbclient.ClientConfig(username=user, password=password, require_secure_negotiate=verify)
config.domain_controller = dc
```

**Comment by Bargenish** [comment]
@jborean93 the `user` and `password` args are being set with a value other than `None`.
Thanks! will try that 🙂

**Comment by Bargenish** [comment]
Closing as this trick did the job.
Thanks

**Comment by jborean93** [comment]
Glad the workaround works for now, hopefully the next release will include a bugfix where this isn't necessary.

**Comment by dhirschfeld** [comment]
There's no linked PR here and I can't see anything in the release notes of 1.6.0/1 - has this issue actually been fixed in the most recent release?

**Comment by jborean93** [comment]
Looks like it was not, must have missed it as I wasn’t looking at the closed issues.

**Comment by dhirschfeld** [comment]
Good to know as I'm seeing this error message with 1.6.1 so was hoping it wasn't some mystery new issue! I'll give the workaround a go in the interim...

**Comment by jborean93** [comment]
The error message is a byproduct of the underlying problem. Are you seeing this when setting the domain controller for DFS or is this some other scenario?

**Comment by dhirschfeld** [comment]
Not too sure - only just noticed it tonight, so a debugging project for Monday! 😅

**Comment by jborean93** [comment]
The PR https://github.com/jborean93/smbprotocol/pull/133 should fix this particular problem.

**Comment by jborean93** [comment]
1.6.2 has just been published on PyPI with this fix https://pypi.org/project/smbprotocol/1.6.2/.
