### ISSUE TITLE
Login failure with AWS file gateway and SMBv3

### ISSUE THREAD

**Issue by jmandawg** [jborean93/smbprotocol#111]
Hi,

we are using the smbprotocol library for connecting to an AWS file gateway share using SMBv3.  
AWS pushed out an update last night and now we can no longer connect via python. 

We can connect via windows and mac using the same credentials.  

This was working fine yesterday.

Here is the debug output, any suggestions?

```
INFO:smbprotocol.connection:Initialising connection, guid: 48176a35-5242-4f46-8059-627d0f059c4d, require_signing: True, server_name: xx.xx.xx.171, port: 445
INFO:smbprotocol.connection:Setting up transport connection
INFO:smbprotocol.transport:Connecting to DirectTcp socket
DEBUG:smbprotocol.transport:Socket recv(4) (total 4)
INFO:smbprotocol.connection:Starting negotiation with SMB server
INFO:smbprotocol.connection:Negotiating with SMB2 protocol with highest client dialect of: SMB_3_1_1
DEBUG:smbprotocol.connection:Adding client guid 48176a35-5242-4f46-8059-627d0f059c4d to negotiate request
DEBUG:smbprotocol.connection:Adding client capabilities 69 to negotiate request
DEBUG:smbprotocol.connection:Adding preauth integrity capabilities of hash SHA512 and salt b'L<\xa6\xaazY]H\xb7M\x9d\x16\x92t\xc8\xd4\x85\x01Z\xd6\xba\xa1L\x1e~\xaf\xc5N\xb0_eY' to negotiate request
DEBUG:smbprotocol.connection:Adding encryption capabilities of AES128 GCM and AES128 CCM to negotiate request
INFO:smbprotocol.connection:Sending SMB2 Negotiate message
DEBUG:smbprotocol.connection:SMB3NegotiateRequest:
    structure_size = 36
    dialect_count = 5
    security_mode = (2) SMB2_NEGOTIATE_SIGNING_REQUIRED
    reserved = 0
    capabilities = (69) SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_ENCRYPTION, SMB2_GLOBAL_CAP_LARGE_MTU
    client_guid = 48176a35-5242-4f46-8059-627d0f059c4d
    negotiate_context_offset = 112
    negotiate_context_count = 2
    reserved2 = 0
    dialects = [
        (514) SMB_2_0_2,
        (528) SMB_2_1_0,
        (768) SMB_3_0_0,
        (770) SMB_3_0_2,
        (785) SMB_3_1_1
    ]
    padding = 00 00
    negotiate_context_list = [
        SMB2NegotiateContextRequest:
            context_type = (1) SMB2_PREAUTH_INTEGRITY_CAPABILITIES
            data_length = 38
            reserved = 0
            data =
            SMB2PreauthIntegrityCapabilities:
                hash_algorithm_count = 1
                salt_length = 32
                hash_algorithms = [
                    (1) SHA_512
                ]
                salt = 4C 3C A6 AA 7A 59 5D 48 B7 4D 9D 16 92 74 C8 D4 85 01 5A D6 BA A1 4C 1E 7E AF C5 4E B0 5F 65 59

                Raw Hex:
                    01 00 20 00 01 00 4C 3C
                    A6 AA 7A 59 5D 48 B7 4D
                    9D 16 92 74 C8 D4 85 01
                    5A D6 BA A1 4C 1E 7E AF
                    C5 4E B0 5F 65 59
            padding = 00 00

            Raw Hex:
                01 00 26 00 00 00 00 00
                01 00 20 00 01 00 4C 3C
                A6 AA 7A 59 5D 48 B7 4D
                9D 16 92 74 C8 D4 85 01
                5A D6 BA A1 4C 1E 7E AF
                C5 4E B0 5F 65 59 00 00,
        SMB2NegotiateContextRequest:
            context_type = (2) SMB2_ENCRYPTION_CAPABILITIES
            data_length = 6
            reserved = 0
            data =
            SMB2EncryptionCapabilities:
                cipher_count = 2
                ciphers = [
                    (2) AES_128_GCM,
                    (1) AES_128_CCM
                ]

                Raw Hex:
                    02 00 02 00 01 00
            padding =

            Raw Hex:
                02 00 06 00 00 00 00 00
                02 00 02 00 01 00
    ]

    Raw Hex:
        24 00 05 00 02 00 00 00
        45 00 00 00 48 17 6A 35
        52 42 4F 46 80 59 62 7D
        0F 05 9C 4D 70 00 00 00
        02 00 00 00 02 02 10 02
        00 03 02 03 11 03 00 00
        01 00 26 00 00 00 00 00
        01 00 20 00 01 00 4C 3C
        A6 AA 7A 59 5D 48 B7 4D
        9D 16 92 74 C8 D4 85 01
        5A D6 BA A1 4C 1E 7E AF
        C5 4E B0 5F 65 59 00 00
        02 00 06 00 00 00 00 00
        02 00 02 00 01 00
DEBUG:smbprotocol.transport:Socket recv() returned 4 bytes (total 4)
DEBUG:smbprotocol.transport:Socket recv(284) (total 284)
DEBUG:smbprotocol.transport:Socket recv() returned 284 bytes (total 284)
DEBUG:smbprotocol.transport:Socket recv(4) (total 4)
INFO:smbprotocol.connection:Receiving SMB2 Negotiate response
DEBUG:smbprotocol.connection:SMB2HeaderResponse:
    protocol_id = FE 53 4D 42
    structure_size = 64
    credit_charge = 0
    status = (0) STATUS_SUCCESS
    command = (0) SMB2_NEGOTIATE
    credit_response = 1
    flags = (1) SMB2_FLAGS_SERVER_TO_REDIR
    next_command = 0
    message_id = 0
    reserved = 0
    tree_id = 0
    session_id = 0
    signature = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    data = 41 00 01 00 11 03 02 00 73 67 77 2D 30 62 31 38 66 62 36 32 00 00 00 00 07 00 00 00 00 00 80 00 00 00 80 00 00 00 80 00 DA EF 8A 4E 93 59 D7 01 00 00 00 00 00 00 00 00 80 00 60 00 E0 00 00 00 60 5E 06 06 2B 06 01 05 05 02 A0 54 30 52 A0 24 30 22 06 09 2A 86 48 82 F7 12 01 02 02 06 09 2A 86 48 86 F7 12 01 02 02 06 0A 2B 06 01 04 01 82 37 02 02 0A A3 2A 30 28 A0 26 1B 24 6E 6F 74 5F 64 65 66 69 6E 65 64 5F 69 6E 5F 52 46 43 34 31 37 38 40 70 6C 65 61 73 65 5F 69 67 6E 6F 72 65 01 00 26 00 00 00 00 00 01 00 20 00 01 00 82 B4 E0 34 AB 66 35 83 8B 68 38 14 7E D2 B5 FD 5E A1 70 7E 4C 98 F5 05 30 58 AC D5 1A 91 0F 02 00 00 02 00 04 00 00 00 00 00 01 00 01 00

    Raw Hex:
        FE 53 4D 42 40 00 00 00
        00 00 00 00 00 00 01 00
        01 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        41 00 01 00 11 03 02 00
        73 67 77 2D 30 62 31 38
        66 62 36 32 00 00 00 00
        07 00 00 00 00 00 80 00
        00 00 80 00 00 00 80 00
        DA EF 8A 4E 93 59 D7 01
        00 00 00 00 00 00 00 00
        80 00 60 00 E0 00 00 00
        60 5E 06 06 2B 06 01 05
        05 02 A0 54 30 52 A0 24
        30 22 06 09 2A 86 48 82
        F7 12 01 02 02 06 09 2A
        86 48 86 F7 12 01 02 02
        06 0A 2B 06 01 04 01 82
        37 02 02 0A A3 2A 30 28
        A0 26 1B 24 6E 6F 74 5F
        64 65 66 69 6E 65 64 5F
        69 6E 5F 52 46 43 34 31
        37 38 40 70 6C 65 61 73
        65 5F 69 67 6E 6F 72 65
        01 00 26 00 00 00 00 00
        01 00 20 00 01 00 82 B4
        E0 34 AB 66 35 83 8B 68
        38 14 7E D2 B5 FD 5E A1
        70 7E 4C 98 F5 05 30 58
        AC D5 1A 91 0F 02 00 00
        02 00 04 00 00 00 00 00
        01 00 01 00
INFO:smbprotocol.connection:Negotiated dialect: (785) SMB_3_1_1
INFO:smbprotocol.connection:Connection require signing: True
INFO:smbprotocol.session:Initialising session with username: svcaccount
DEBUG:smbprotocol.session:Decoding SPNEGO token containing supported auth mechanisms
DEBUG:spnego.negotiate:SPNEGO step input: YF4GBisGAQUFAqBUMFKgJDAiBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICCqMqMCigJhskbm90X2RlZmluZWRfaW5fUkZDNDE3OEBwbGVhc2VfaWdub3Jl
DEBUG:spnego.negotiate:SPNEGO step output: YEAGBisGAQUFAqA2MDSgDjAMBgorBgEEAYI3AgIKoiIEIE5UTE1TU1AAAQAAADeCCOAAAAAAIAAAAAAAAAAgAAAA
INFO:smbprotocol.session:Sending SMB2_SESSION_SETUP request message
INFO:smbprotocol.session:Receiving SMB2_SESSION_SETUP response message
DEBUG:smbprotocol.transport:Socket recv() returned 4 bytes (total 4)
DEBUG:smbprotocol.transport:Socket recv(301) (total 301)
DEBUG:smbprotocol.transport:Socket recv() returned 301 bytes (total 301)
DEBUG:smbprotocol.transport:Socket recv(4) (total 4)
INFO:smbprotocol.session:More processing is required for SMB2_SESSION_SETUP
DEBUG:spnego.negotiate:SPNEGO step input: oYHiMIHfoAMKAQGhDAYKKwYBBAGCNwICCqKByQSBxk5UTE1TU1AAAgAAAAQABAA4AAAANYKJ4kVCZBaWExLkAAAAAAAAAACKAIoAPAAAAAYBAAAAAAAPVQBTAAIABABVAFMAAQAYAFMARwBXAC0AMABCADEAOABGAEIANgAyAAQAGAB1AHMALgBhAGUAZwBvAG4ALgBjAG8AbQADADYAaQBwAC0AMQAwAC0ANAA1AC0AMQAtADEANwAxAC4AdQBzAC4AYQBlAGcAbwBuAC4AYwBvAG0ABwAIAEzMpU6TWdcBAAAAAA==
DEBUG:spnego.negotiate:SPNEGO step output: oYIBwzCCAb+gAwoBAaKCAaIEggGeTlRMTVNTUAADAAAAGAAYAFgAAADmAOYAcAAAAAAAAABWAQAAIAAgAFYBAAAYABgAdgEAABAAEACOAQAANYKJ4gABBgAAAAAPGXGT6ReASmlMin1CJIh1ogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALQXMerGquIhZ52SjWH151kBAQAAAAAAAEzMpU6TWdcBxMR9go6ktZgAAAAAAgAEAFUAUwABABgAUwBHAFcALQAwAEIAMQA4AEYAQgA2ADIABAAYAHUAcwAuAGEAZQBnAG8AbgAuAGMAbwBtAAMANgBpAHAALQAxADAALQA0ADUALQAxAC0AMQA3ADEALgB1AHMALgBhAGUAZwBvAG4ALgBjAG8AbQAHAAgATMylTpNZ1wEJACAAQwBJAEYAUwAvADEAMAAuADQANQAuADEALgAxADcAMQAGAAQAAgAAAAAAAAAAAAAAcwB2AGMAdABlAGIAdABlAGMAaABhAHAAaQB0AHMAdABDADAAMgBDADEAMQAzAEQATQBEADYAUABiQVkueIc15qe8xs/QzQhooxIEEAEAAACqm5PWRtdKCwAAAAA=
INFO:smbprotocol.session:Sending SMB2_SESSION_SETUP request message
INFO:smbprotocol.session:Receiving SMB2_SESSION_SETUP response message
DEBUG:smbprotocol.transport:Socket recv() returned 4 bytes (total 4)
DEBUG:smbprotocol.transport:Socket recv(73) (total 73)
DEBUG:smbprotocol.transport:Socket recv() returned 73 bytes (total 73)
DEBUG:smbprotocol.transport:Socket recv(4) (total 4)
Traceback (most recent call last):
  File "moveFileSample.py", line 10, in <module>
    smbclient.register_session("xx.xx.xx.171", username="svcaccount", password="XXXXXX")
  File "/Users/jomoon/Library/Python/3.8/lib/python/site-packages/smbclient/_pool.py", line 360, in register_session
    session.connect()
  File "/Users/jomoon/Library/Python/3.8/lib/python/site-packages/smbprotocol/session.py", line 292, in connect
    response = self.connection.receive(request)
  File "/Users/jomoon/Library/Python/3.8/lib/python/site-packages/smbprotocol/connection.py", line 928, in receive
    raise SMBResponseException(response)
smbprotocol.exceptions.LogonFailure: Received unexpected status from the server: The attempted logon is invalid. This is either due to a bad username or authentication information. (3221225581) STATUS_LOGON_FAILURE: 0xc000006d
INFO:smbprotocol.connection:Disconnecting transport connection
INFO:smbprotocol.transport:Disconnecting DirectTcp socket
DEBUG:smbprotocol.transport:Socket recv() returned 0 bytes (total 4)
```

**Comment by jborean93** [comment]
Nothing is jumping out at the logs and I can't find anything that might be wrong in the auth tokens. There are 2 things you can do:

1. See if there are any audit logs on the AWS side that might indicate why it's rejecting the logon
2. Compare the SMB traffic from the native Windows/macOS client and this one

The key things you want to compare are the authentication token, in this case the last `SPNEGO step output` is the key token here but comparing the rest might bring up some other differences. You can run `python -m spnego --token <base64 value>` to get a human readable representation of the token.

For example the first token in your logs is

```yaml
# python -m spnego --format yaml --token YF4GBisGAQUFAqBUMFKgJDAiBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICCqMqMCigJhskbm90X2RlZmluZWRfaW5fUkZDNDE3OEBwbGVhc2VfaWdub3Jl
MessageType: SPNEGO InitialContextToken
Data:
  thisMech: SPNEGO (1.3.6.1.5.5.2)
  innerContextToken:
    MessageType: SPNEGO NegTokenInit2
    Data:
      mechTypes:
      - MS Kerberos (1.2.840.48018.1.2.2)
      - Kerberos (1.2.840.113554.1.2.2)
      - NTLM (1.3.6.1.4.1.311.2.2.10)
      reqFlags:
      mechToken:
      mechListMIC:
      negHints:
        hintName: not_defined_in_RFC4178@please_ignore
        hintAddress:
    RawData: A0543052A024302206092A864882F71201020206092A864886F712010202060A2B06010401823702020AA32A3028A0261B246E6F745F646566696E65645F696E5F5246433431373840706C656173655F69676E6F7265
RawData: 605E06062B0601050502A0543052A024302206092A864882F71201020206092A864886F712010202060A2B06010401823702020AA32A3028A0261B246E6F745F646566696E65645F696E5F5246433431373840706C656173655F69676E6F7265
```

The last token (edited for brevity is):

```yaml
# python -m spnego --format yaml --token oYIBwzCCAb+gAwoBAaKCAaIEggGeTlRMTVNTUAADAAAAGAAYAFgAAADmAOYAcAAAAAAAAABWAQAAIAAgAFYBAAAYABgAdg
EAABAAEACOAQAANYKJ4gABBgAAAAAPGXGT6ReASmlMin1CJIh1ogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALQXMerGquIhZ52SjWH151kBAQAAAAAAAEzMpU6TWdcBxMR9go6ktZgAAAAAAgAEAFUAUwABABgAUwBHAFcALQAwAEIAMQA4AEYAQgA2ADIABAAYAHUAc
wAuAGEAZQBnAG8AbgAuAGMAbwBtAAMANgBpAHAALQAxADAALQA0ADUALQAxAC0AMQA3ADEALgB1AHMALgBhAGUAZwBvAG4ALgBjAG8AbQAHAAgATMylTpNZ1wEJACAAQwBJAEYAUwAvADEAMAAuADQANQAuADEALgAxADcAMQAGAAQAAgAAAAAAAAAAAAAAcwB2AGMA
dABlAGIAdABlAGMAaABhAHAAaQB0AHMAdABDADAAMgBDADEAMQAzAEQATQBEADYAUABiQVkueIc15qe8xs/QzQhooxIEEAEAAACqm5PWRtdKCwAAAAA=
MessageType: SPNEGO NegTokenResp
Data:
  negState: accept-incomplete (1)
  supportedMech:
  responseToken:
    MessageType: AUTHENTICATE_MESSAGE (3)
    Data:
      ...
      NegotiateFlags:
        raw: 3800662581
        flags:
        - NTLMSSP_NEGOTIATE_56 (2147483648)
        - NTLMSSP_NEGOTIATE_KEY_EXCH (1073741824)
        - NTLMSSP_NEGOTIATE_128 (536870912)
        - NTLMSSP_NEGOTIATE_VERSION (33554432)
        - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
        - NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY (524288)
        - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
        - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
        - NTLMSSP_NEGOTIATE_NTLM (512)
        - NTLMSSP_NEGOTIATE_SEAL (32)
        - NTLMSSP_NEGOTIATE_SIGN (16)
        - NTLMSSP_REQUEST_TARGET (4)
        - NTLMSSP_NEGOTIATE_UNICODE (1)
      MIC: 197193E917804A694C8A7D42248875A2
      Payload:
        LmChallengeResponse:
          ResponseType: LMv1
          LMProofStr: '000000000000000000000000000000000000000000000000'
        NtChallengeResponse:
          ResponseType: NTLMv2
          NTProofStr: ...
          ClientChallenge:
            RespType: 1
            HiRespType: 1
            Reserved1: 0
            Reserved2: 0
            TimeStamp: '2021-06-04T22:45:24.527214Z'
            ChallengeFromClient: C4C47D828EA4B598
            Reserved3: 0
            AvPairs:
            - AvId: MSV_AV_NB_DOMAIN_NAME (2)
              Value: ...
            - AvId: MSV_AV_NB_COMPUTER_NAME (1)
              Value: ...
            - AvId: MSV_AV_DNS_DOMAIN_NAME (4)
              Value: ...
            - AvId: MSV_AV_DNS_COMPUTER_NAME (3)
              Value: ...
            - AvId: MSV_AV_TIMESTAMP (7)
              Value: '2021-06-04T22:45:24.527214Z'
            - AvId: MSV_AV_TARGET_NAME (9)
              Value: CIFS/...
            - AvId: MSV_AV_FLAGS (6)
              Value:
                raw: 2
                flags:
                - MIC_PROVIDED (2)
            - AvId: MSV_AV_EOL (0)
              Value:
            Reserved4: 0
        DomainName:
        UserName: ...
        Workstation: ...
        EncryptedRandomSessionKey: 6241592E788735E6A7BCC6CFD0CD0868
      SessionKey: Failed to derive
  mechListMIC: 01000000AA9B93D646D74A0B00000000
```

Some important things to note here

* The `AvPairs` are based on the challenge from the server, I'm mostly blanked them out for this output but run the command yourself to see the true values
* The `UserName`, `Workstation` and `NtProofStr` are also blanked out for this log
* The `mechListMIC` is part of SPNEGO, I've recently seen a suspicious report where Windows didn't send this while this library did causing a failure but I was never able to replicate this behaviour myself - https://github.com/jborean93/smbprotocol/issues/89#issuecomment-822727743

Comparing this last message and seeing what the differences are would be quite helpful to try and track down what is happening.

**Comment by jmandawg** [comment]
Ok so.after more troubleshooting it appears as though due to the AWS update we have to have the domain prefix on the username ie "FOO\username".  Thanks.
