### ISSUE TITLE
IPv6 and v6 link-local not supported

### ISSUE THREAD

**Issue by killsudo** [jborean93/smbprotocol#24]
The following fails on IPv6 global addresses and IPv6 link-local but a IPv4 addresses works successfully.

```
#!/usr/bin/env python3

from pypsexec.client import Client

# creates an encrypted connection to the host with the username and password
c = Client('[fe80::250:56ff:feab:9405%ens192]', username="Administrator", password="somepass")

c.connect()
try:
    c.create_service()

    # After creating the service, you can run multiple exe's without
    # reconnecting

    # run a simple cmd.exe program with arguments
    result = c.run_executable("cmd.exe",
                              arguments="/c echo Hello World")
finally:
    c.remove_service()
    c.disconnect()

print("STDOUT:\n%s" % result[0].decode('utf-8') if result[0] else "")
print("STDERR:\n%s" % result[1].decode('utf-8') if result[1] else "")
print("RC: %d" % result[2])
```

Port 445 is open via IPv6

```
[root@jumphost ~]# telnet fe80::250:56ff:feab:9405%ens192 445
Trying fe80::250:56ff:feab:9405%ens192...
Connected to fe80::250:56ff:feab:9405%ens192.
Escape character is '^]'.
^]
telnet> quit
```

Error Message:

```
[root@jumphost ~]# python3 psexec_test.py                        
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/transport.py", line 57, in wrapped
    self._sock = socket.create_connection((self.server, self.port), timeout=self.timeout)
  File "/usr/lib64/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "psexec_test.py", line 11, in <module>
    c.connect()
  File "/usr/local/lib/python3.6/site-packages/pypsexec/client.py", line 60, in connect
    self.connection.connect(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 881, in connect
    smb_response = self._send_smb2_negotiate(dialect, timeout)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 1446, in _send_smb2_negotiate
    request = self.send(neg_req)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 966, in send
    async_id=async_id)[0]
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 763, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 1244, in _send
    self.transport.send(send_data)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/transport.py", line 59, in wrapped
    raise ValueError("Failed to connect to '%s:%s': %s" % (self.server, self.port, str(err)))
ValueError: Failed to connect to '[fe80::250:56ff:feab:9405%ens192]:445': [Errno -2] Name or service not known
```

**Comment by jborean93** [comment]
I thought I fixed this, try removing the `[]` in the address, e.g.

```
c = Client('fe80::250:56ff:feab:9405%ens192', username="Administrator", password="somepass")
```

**Comment by killsudo** [comment]
You did! I actually realized right after this post that I hadn't tried without the [] and I was able to confirm it worked perfectly.

Going to post the following for anyone in the future that is curious in using pypsexec with IPv6 link-local and powershell against Windows.

```
#!/usr/bin/env python3

from pypsexec.client import Client

# creates an encrypted connection to the host with the username and password
c = Client('fe80::250:56ff:feab:9405%ens192', username="Administrator", password="somepass")

c.connect()
try:
    c.create_service()

    # After creating the service, you can run multiple exe's without
    # reconnecting

    # run some powershell cmdlets with arguments

    result = c.run_executable("powershell.exe",
                              arguments="Get-NetAdapter | Select-Object Name | ConvertTo-Json")

finally:
    c.remove_service()
    c.disconnect()

print("STDOUT:\n%s" % result[0].decode('utf-8') if result[0] else "")
print("STDERR:\n%s" % result[1].decode('utf-8') if result[1] else "")
print("RC: %d" % result[2])
```

```
[root@jumphost ~]# python3 psexec_test.py
STDOUT:
{
    "Name":  "Ethernet0"
}


RC: 0
```

**Comment by jborean93** [comment]
Awesome, thanks for confirming. Was really hoping I didn't mess up somewhere :).
