### ISSUE TITLE
Use Azure File Storage to transfer files

### ISSUE THREAD

**Issue by ThomasUllrich666** [jborean93/smbprotocol#40]
Hi all. 
I like to use the smb functionality of Microsoft Azure Filestorage to transfer files via SMB .

Unfortunately I receive the following error: **pyasn1.error.SubstrateUnderrunError: Short octet stream on tag decoding**

If I have a closer look to the Session.connect methode I see that the self.connection.gss_negotiate_token value is empty. 

I used the example python file of this project. 

Here is the log:
```
INFO:smbprotocol.connection:Initialising connection, guid: 693fa1c0-1ddd-4a0a-b3a6-b4173beff67a, require_singing: True, server_name: foo.file.core.windows.net, port: 445
INFO:smbprotocol.connection:Setting up transport connection
INFO:smbprotocol.connection:Starting negotiation with SMB server
INFO:smbprotocol.connection:Negotiating with SMB2 protocol with highest client dialect of: SMB_3_1_1
DEBUG:smbprotocol.connection:Adding client guid 693fa1c0-1ddd-4a0a-b3a6-b4173beff67a to negotiate request
DEBUG:smbprotocol.connection:Adding client capabilities 68 to negotiate request
DEBUG:smbprotocol.connection:Adding preauth integrity capabilities of hash SHA512 and salt b'\x1aJ\x87pb;\xa2zt\xe7\x0f\xd7\x1d5\x02`\xf3\xc6\xa4\x90\xac\xeel$B\x13\xa3\xdevv\x91\xcd' to negotiate request
DEBUG:smbprotocol.connection:Adding encryption capabilities of AES128 GCM and AES128 CCM to negotiate request
INFO:smbprotocol.connection:Sending SMB2 Negotiate message
DEBUG:smbprotocol.connection:SMB3NegotiateRequest:
    structure_size = 36
    dialect_count = 5
    security_mode = (2) SMB2_NEGOTIATE_SIGNING_REQUIRED
    reserved = 0
    capabilities = (68) SMB2_GLOBAL_CAP_ENCRYPTION, SMB2_GLOBAL_CAP_LARGE_MTU
    client_guid = 693fa1c0-1ddd-4a0a-b3a6-b4173beff67a
    negotiate_context_offset = 112
    negotiate_context_count = 2
    reserved2 = 0
    dialects = [
        (514) SMB_2_0_2,
        (528) SMB_2_1_0,
        (768) SMB_3_0_0,
        (770) SMB_3_0_2,
        (785) SMB_3_1_1
    ]
    padding = 00 00
    negotiate_context_list = [
        SMB2NegotiateContextRequest:
            context_type = (1) SMB2_PREAUTH_INTEGRITY_CAPABILITIES
            data_length = 38
            reserved = 0
            data =
            SMB2PreauthIntegrityCapabilities:
                hash_algorithm_count = 1
                salt_length = 32
                hash_algorithms = [
                    (1) SHA_512
                ]
                salt = 1A 4A 87 70 62 3B A2 7A 74 E7 0F D7 1D 35 02 60 F3 C6 A4 90 AC EE 6C 24 42 13 A3 DE 76 76 91 CD

                Raw Hex:
                    01 00 20 00 01 00 1A 4A
                    87 70 62 3B A2 7A 74 E7
                    0F D7 1D 35 02 60 F3 C6
                    A4 90 AC EE 6C 24 42 13
                    A3 DE 76 76 91 CD
            padding = 00 00

            Raw Hex:
                01 00 26 00 00 00 00 00
                01 00 20 00 01 00 1A 4A
                87 70 62 3B A2 7A 74 E7
                0F D7 1D 35 02 60 F3 C6
                A4 90 AC EE 6C 24 42 13
                A3 DE 76 76 91 CD 00 00,
        SMB2NegotiateContextRequest:
            context_type = (2) SMB2_ENCRYPTION_CAPABILITIES
            data_length = 6
            reserved = 0
            data =
            SMB2EncryptionCapabilities:
                cipher_count = 2
                ciphers = [
                    (2) AES_128_GCM,
                    (1) AES_128_CCM
                ]

                Raw Hex:
                    02 00 02 00 01 00
            padding = 

            Raw Hex:
                02 00 06 00 00 00 00 00
                02 00 02 00 01 00
    ]

    Raw Hex:
        24 00 05 00 02 00 00 00
        44 00 00 00 69 3F A1 C0
        1D DD 4A 0A B3 A6 B4 17
        3B EF F6 7A 70 00 00 00
        02 00 00 00 02 02 10 02
        00 03 02 03 11 03 00 00
        01 00 26 00 00 00 00 00
        01 00 20 00 01 00 1A 4A
        87 70 62 3B A2 7A 74 E7
        0F D7 1D 35 02 60 F3 C6
        A4 90 AC EE 6C 24 42 13
        A3 DE 76 76 91 CD 00 00
        02 00 06 00 00 00 00 00
        02 00 02 00 01 00
INFO:smbprotocol.transport:Connecting to DirectTcp socket
INFO:smbprotocol.connection:Receiving SMB2 Negotiate response
DEBUG:smbprotocol.connection:SMB2HeaderResponse:
    protocol_id = FE 53 4D 42
    structure_size = 64
    credit_charge = 0
    status = (0) STATUS_SUCCESS
    command = (0) SMB2_NEGOTIATE
    credit_response = 1
    flags = (1) SMB2_FLAGS_SERVER_TO_REDIR
    next_command = 0
    message_id = 0
    reserved = 0
    tree_id = 0
    session_id = 0
    signature = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    data = 41 00 03 00 00 03 00 00 95 AB 1A 2F 2F 08 88 46 9D 2B 0B F5 CF 4A 01 3A 47 00 00 00 00 00 10 00 00 00 10 00 00 00 10 00 60 87 E7 05 8D 3D D6 01 00 00 00 00 00 00 00 00 80 00 00 00 00 00 00 00

    Raw Hex:
        FE 53 4D 42 40 00 00 00
        00 00 00 00 00 00 01 00
        01 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        00 00 00 00 00 00 00 00
        41 00 03 00 00 03 00 00
        95 AB 1A 2F 2F 08 88 46
        9D 2B 0B F5 CF 4A 01 3A
        47 00 00 00 00 00 10 00
        00 00 10 00 00 00 10 00
        60 87 E7 05 8D 3D D6 01
        00 00 00 00 00 00 00 00
        80 00 00 00 00 00 00 00
INFO:smbprotocol.connection:Negotiated dialect: (768) SMB_3_0_0
INFO:smbprotocol.connection:Connection require signing: True
INFO:smbprotocol.session:Initialising session with username: Azure\foo
DEBUG:smbprotocol.session:Decoding SPNEGO token containing supported auth mechanisms
ERROR:root:Fatal error during test:
Traceback (most recent call last):
  File "c:\fpo\foo-WorkpieceImporterPy\workpieceImporter\filesystemExporter.py", line 29, in <module>
    session.connect()
  File "C:\Program Files\Python37\lib\site-packages\smbprotocol\session.py", line 288, in connect
    asn1Spec=InitialContextToken())
  File "C:\Program Files\Python37\lib\site-packages\pyasn1\codec\ber\decoder.py", line 1338, in __call__
    'Short octet stream on tag decoding'
pyasn1.error.SubstrateUnderrunError: Short octet stream on tag decoding
INFO:smbprotocol.connection:Disconnecting transport connection
INFO:smbprotocol.transport:Disconnecting DirectTcp socket
```

**Comment by jborean93** [comment]
Thanks for reporting this, just so I don't forget when I come back to this, the SMB2 Negotiate Response in that header is

```
SMB2NegotiateResponse:
    structure_size = 65
    security_mode = (3) SMB2_NEGOTIATE_SIGNING_ENABLED, SMB2_NEGOTIATE_SIGNING_REQUIRED
    dialect_revision = (768) SMB_3_0_0
    negotiate_context_count = 0
    server_guid = 95ab1a2f-2f08-8846-9d2b-0bf5cf4a013a
    capabilities = (71) SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_ENCRYPTION, SMB2_GLOBAL_CAP_LARGE_MTU, SMB2_GLOBAL_CAP_LEASING
    max_transact_size = 1048576
    max_read_size = 1048576
    max_write_size = 1048576
    system_time = 2020-06-08 12:04:55.275094
    server_start_time = 1601-01-01 00:00:00
    security_buffer_offset = 128
    security_buffer_length = 0
    negotiate_context_offset = 0
    buffer = 
    padding = 
    negotiate_context_list = []

    Raw Hex:
        41 00 03 00 00 03 00 00
        95 AB 1A 2F 2F 08 88 46
        9D 2B 0B F5 CF 4A 01 3A
        47 00 00 00 00 00 10 00
        00 00 10 00 00 00 10 00
        5C 87 E7 05 8D 3D D6 01
        00 00 00 00 00 00 00 00
        80 00 00 00 00 00 00 00
```

In all scenarios that I've ever tested the `buffer` field contains the SPNEGO token that defines what authentication capabilities the server supports but in this case it seems like Azure isn't sending one. Looks like I need to change the code to handle such a scenario and get it to kick off the SPNEGO process itself.

**Comment by ThomasUllrich666** [comment]
Hi @jborean93,
thanks for your feedback. It would be nice if you can do this.  Do you have an Azure Storage to test it? Otherwise I can run you UnitTests towards the Azure SMB storage.

**Comment by jborean93** [comment]
I just create a test share on Azure and was able to test out this scenario. While the changes are not ready, the [auth](https://github.com/jborean93/smbprotocol/tree/auth) branch contains the changes necessary to get this working.

That branch is a pretty major change in the way authentication works and offloads all the logic to another library that can handle all this correctly. I'm hoping to have it ready soon but I need to test out a few more scenarios before it is ready for prime time.
