### ISSUE TITLE
STATUS_NETWORK_SESSION_EXPIRED not handled

### ISSUE THREAD

**Issue by rob-blackbourn** [jborean93/smbprotocol#90]
I have a long running process. After "a while" it fails to write with the following:

```python
Traceback (most recent call last):
  File "/home/worker/venv/lib/python3.8/site-packages/smbclient/_io.py", line 368, in open
    open_result = self.fd.create(
  File "/home/worker/venv/lib/python3.8/site-packages/smbprotocol/open.py", line 1213, in create
    return self._create_response(request)
  File "/home/worker/venv/lib/python3.8/site-packages/smbprotocol/open.py", line 1219, in _create_response
    response = self.connection.receive(request)
  File "/home/worker/venv/lib/python3.8/site-packages/smbprotocol/connection.py", line 928, in receive
    raise SMBResponseException(response)
smbprotocol.exceptions.SMBResponseException: Received unexpected status from the server: Unknown error. (3221226332) UNKNOWN_ENUM: 0xc000035c
```

Looking [here](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb/6ab6ca20-b404-41fd-b91a-2ed39e3762ea) I can see this corresponds to `STATUS_NETWORK_SESSION_EXPIRED`.

Is there a way to handle this?

**Comment by jborean93** [comment]
Unfortunately this isn't implement yet, the docs for re authenticating an expired session can be found at https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/d11845f6-c848-4255-960a-eb8f46f3e703 but a lot of this logic is internal in the `session.py` file.

You could try to reset your connection after that pause with `smbclient.reset_connection_cache()` to ensure the subsequent commands are done with a new session.

**Comment by rob-blackbourn** [comment]
Thanks. I'll give that a try.
