### ISSUE TITLE
Kerberos authentication fails for a third party SMB server

### ISSUE THREAD

**Issue by balalnx16** [jborean93/smbprotocol#92]
I'm` a using a third party SMB server, SMB mount with kerberos fails with the following debug logs

>/home/cohesity/.local/lib/python2.7/site-packages/smbprotocol/connection.py:21: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import (
2021-04-22 20:10:31,103 - smbprotocol.session - INFO - Initialising session with username: fp_6@W2K16-0.QA.LOCAL
2021-04-22 20:10:31,103 - smbprotocol.session - DEBUG - Decoding SPNEGO token containing supported auth mechanisms
2021-04-22 20:10:31,103 - spnego.gss - DEBUG - GSSAPI does not support required the NTLM interfaces: Major (65536): An unsupported mechanism was requested, Minor (0): Unknown error
<spnego.negotiate.NegotiateProxy object at 0x7f4fe0742310>
2021-04-22 20:10:31,103 - spnego.negotiate - DEBUG - SPNEGO step input: YFIGBisGAQUFAqBIMEagGDAWBgkqhkiC9xIBAgIGCSqGSIb3EgECAqMqMCigJhskbm90X2RlZmluZWRfaW5fUkZDNDE3OEBwbGVhc2VfaWdub3Jl
2021-04-22 20:10:31,105 - spnego.gss - DEBUG - GSSAPI step input: 
2021-04-22 20:10:31,105 - spnego.gss - DEBUG - before _context.step
2021-04-22 20:10:31,105 - spnego.gss - DEBUG - <gssapi.sec_contexts.SecurityContext object at 0x7f4fe0744640>
2021-04-22 20:10:31,112 - spnego.gss - DEBUG - after _context.step
2021-04-22 20:10:31,112 - spnego.gss - DEBUG - success
2021-04-22 20:10:31,112 - spnego.negotiate - DEBUG - Success
2021-04-22 20:10:31,112 - spnego.negotiate - DEBUG - in step 2
2021-04-22 20:10:31,112 - spnego.negotiate - DEBUG - <spnego.gss.GSSAPIProxy object at 0x7f4fe07424d0>
2021-04-22 20:10:31,112 - spnego.negotiate - DEBUG - if generated_token _step_spnego_token
2021-04-22 20:10:31,112 - spnego.negotiate - DEBUG - in step 3
2021-04-22 20:10:31,112 - spnego.negotiate - DEBUG - in step 4
2021-04-22 20:10:31,113 - spnego.negotiate - DEBUG - SPNEGO step output: YIIGBAYGKwYBBQUCoIIF+DCCBfSgDTALBgkqhkiG9xIBAgKiggXhBIIF3WCCBdkGCSqGSIb3EgECAgEAboIFyDCCBcSgAwIBBaEDAgEOogcDBQAgAAAAo4IE2GGCBNQwggTQoAMCAQWhEhsQVzJLMTYtMC5RQS5MT0NBTKI1MDOgAwIBA6EsMCobBGNpZnMbImZpbGVyLXMtMS1hbGlhcy0zLncyazE2LTAucWEubG9jYWyjggR8MIIEeKADAgESoQMCAQKiggRqBIIEZjKskQ6bAk4ZsR0JTB4q0sMDQKGJTDVzRccEiHBx5G/xA0eC67dgZP+uFIoWYWDDlzmnD9kUsD1tVjL6h7Hw7Mijz/rWNKM5txNpL+U2eftb5nSiIZ6uzf2LZXzTTHe+Fkqs7Ug1B7/bt6wKYwVf4QW57y+u7lRCgLIm8RFY3Xb4ViWpZywZWtuNv5gJBfk17sYy1ASz7XLFZ6a4CtRLGmj52wTibhfHck/3VAI7LrAE34AdeNESqiBakhZkQDHHl6JrEXdY/4TWpMNQ0CHrf60JPXd79PcR691azKM/DsqzeMybldWI6vs29T3fnBRvOnHJnDWlKm7PUGSspi8LHy6zJig93GABUiLhFKZkqACLdXCrh38FUWqZz6QFqg3k8PwzEQqA8iyTK6oQz6p3dFLO2GkMBvykJb7qXGzRjRxlGCU9eSj3tmrOQwtw57Eze4i3p/NFPdE5Mz3ABjgcJleqndyns/uPc3l13rGXg7LkgS0mF5NPgveIteWOmziNK2yCylPzypi6h0l9wMyYTNl36EkuxIEiEc3i/tsVEpDJ4hU3chwjjqW+pplOnx6HI5vRhVMswvcOagz2HylSC8WP/KgvhC8cxN4+PaH08JdN/g9eB2lCEVcfvriMuh+96IbobOdlqy0kFVp2CNNFoygvAMFXBCuFiKXI1hyUjhR5b90gHakxLy5vC5ynVdf8Z4PbQljlP7budTWhcaaqkVPJLLAPo5MGsuy1QHz7ZLLt39/u0j247MXRhZdsnTwHoZNR4pMtlIy+gZB0MebaqqMMJYVNb95Ps974bAiB6EX/HA5pd4BtviKDbCOowNe9xGy7pLIeU6tC+AQomCx548F7QY8VVVADpM9oPd3/GSWPptcyHMbtUSZrG/dbnCZkQnBIdRkMryJ+s1vP9rakihutCfzk+4EQue2Pf7SP6e54UkN5fNbM7H5moV6yTjxoePIW/4EqWxs/QvRw/X7HyrirEr4zmCjGb+H1eEjRitGd3pdsE1D/BD/RUuAY8ugt6QKKereTxjvhhlhYcdPcVs6O01dh0h7ekdXHlEuAxkSnN69+depQRQq6E4crzJ2dzcT17CTkTGxOPes+5eQxFAzdA3INw7txO78hm4Y1b95qomV13MGHb3ir3Lco70CIoy7hBYEMNHf2/FgbmFnm7l7dtUZwG9LKc+67MIQbmS42kffKZvZytSbbkGPPjcsIm0wK7xgew8jM9TtNG0aVd/eW/sC0HOC+J6lDg2d3V5SI7lHxMeQWTuPDplQ6+VMshv/Uy/WqCe/5lPnM17t5z+HZ/aekoC3Mg6P1X5XV3dnywNQP/7VBj6IuTeQIQjnyCVILI8rhnWPGxs24hrXNsEbUs2CMcYTq+9+EI9S1vumoJOw9r5Y7z6YUrArofFmo6SC45f/TmyErrt2D3+hID35Y4FvsFSK5s4sYn8sUN0lVAO84y77ibykoAWjR1luxINwFlRNgmwdiqseQMoT5ZBDpZTJlhNakgdIwgc+gAwIBEqKBxwSBxOXuWBSZDQOlCP3sJUmBvjRMv6uP6acTTWARVyDPDnrH5KXYhPJMZjpwl/eoR18eRFOb/LzrlyzGTNTyvSAeL8gDa1tY+E/2MB0izYeb7ZdvNGcxR/qUMZdOV46aWp0Vn0rmPSwNFm3XvKxDsiCKu75w7e/0wFbYtT6wUvlUquX81JwsR+b3bXfZtPQGCeYtW4d3kyS9B6TwbHqK7gYcHbG0EE338DSbhIbsxlXmZxvt8i7/bSQFJqxQzDJR5YsRMWl1hGg=
2021-04-22 20:10:31,113 - smbprotocol.session - INFO - Sending SMB2_SESSION_SETUP request message
2021-04-22 20:10:31,113 - smbprotocol.session - INFO - Receiving SMB2_SESSION_SETUP response message
2021-04-22 20:10:31,143 - smbprotocol.transport - DEBUG - Socket recv() returned 4 bytes (total 4)
2021-04-22 20:10:31,143 - smbprotocol.transport - DEBUG - Socket recv(258) (total 258)
2021-04-22 20:10:31,143 - smbprotocol.transport - DEBUG - Socket recv() returned 258 bytes (total 258)
2021-04-22 20:10:31,144 - smbprotocol.transport - DEBUG - Socket recv(4) (total 4)
2021-04-22 20:10:31,144 - smbprotocol.session - DEBUG - session id 217411983
2021-04-22 20:10:31,144 - smbprotocol.session - DEBUG - session setup status 0
2021-04-22 20:10:31,144 - spnego.negotiate - DEBUG - SPNEGO step input: oYG3MIG0oAMKAQChCwYJKoZIhvcSAQICooGfBIGcYIGZBgkqhkiG9xIBAgICAG+BiTCBhqADAgEFoQMCAQ+iejB4oAMCARKicQRvxldXKQ719akCp3qftsk2gHEYdUrlh58nff6TA6Qg5IjX1BPvcU6+7hr5dZJooA1LTh3AAcwC7eWcXJP/qeMpxRggPptdwRPjk3uKZNgTN7oa4NXgi4eKOplmMwhJF/ChuFDxhEJUGT0ind9XMYXD
2021-04-22 20:10:31,145 - spnego.negotiate - DEBUG - Success
2021-04-22 20:10:31,145 - spnego.negotiate - DEBUG - in step 2
2021-04-22 20:10:31,145 - spnego.negotiate - DEBUG - <spnego.gss.GSSAPIProxy object at 0x7f4fe07424d0>
2021-04-22 20:10:31,145 - spnego.negotiate - DEBUG - else _step_spnego_token
2021-04-22 20:10:31,145 - spnego.gss - DEBUG - GSSAPI step input: YIGZBgkqhkiG9xIBAgICAG+BiTCBhqADAgEFoQMCAQ+iejB4oAMCARKicQRvxldXKQ719akCp3qftsk2gHEYdUrlh58nff6TA6Qg5IjX1BPvcU6+7hr5dZJooA1LTh3AAcwC7eWcXJP/qeMpxRggPptdwRPjk3uKZNgTN7oa4NXgi4eKOplmMwhJF/ChuFDxhEJUGT0ind9XMYXD
2021-04-22 20:10:31,145 - spnego.gss - DEBUG - before _context.step
2021-04-22 20:10:31,145 - spnego.gss - DEBUG - <gssapi.sec_contexts.SecurityContext object at 0x7f4fe0744640>
2021-04-22 20:10:31,152 - smbprotocol.connection - INFO - Disconnecting transport connection
2021-04-22 20:10:31,152 - smbprotocol.transport - INFO - Disconnecting DirectTcp socket
2021-04-22 20:10:31,152 - smbprotocol.transport - DEBUG - Socket recv() returned 0 bytes (total 4)
Traceback (most recent call last):
  File "smb_test.py", line 39, in <module>
    session.connect()
  File "/home/cohesity/.local/lib/python2.7/site-packages/smbprotocol/session.py", line 283, in connect
    raise SMBAuthenticationError("Failed to authenticate with server: %s" % str(err.message))
smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: SpnegoError (4294967295): Major (131072): An invalid name was supplied, Minor (100001): Success, Context: Processing security token

I added some extra debug messages. 

The failure happens immediately after the server responds for session setup request with NT_STATUS_SUCCESS 

I'm unable to attach the tcpdumps directly, Let me know if I can upload it directly

Any help would be greatly appreciated

**Comment by jborean93** [comment]
The underlying problem is happening at the mutual authentication stage, i.e. when the client is validating the identity of the server. It's essentially erroring with [GSS_BAD_NAME](https://github.com/krb5/krb5/blob/34625d594c339a077899fa01fc4b5c331a1647d0/src/lib/gssapi/mechglue/g_dsp_status.c#L198-L200) which if it was able to generate the initial token with the name but failed when parsing the response means the name did not match it's expectation. This could be an indication of a few things

* The server that responded is not the server you asked for in Kerberos
* Some DNS resolution in the code has gone wrong and it broke the name resolution
* Some other weird Kerberos quirk I don't know about

When you run `pyspnego-parse --token firsttokenbase64` (from the first SPNEGO step output in the logs) you can see what the target host was `cifs@filer-s-1-alias-3.w2k16-0.qa.local`. This SPN must exist in AD or else you would be getting another error so something else might be going wrong here.

Somethings I recommend you try

* Set `smbclient.ClientConfig(auth_protocol='kerberos')` to explicit ask for Kerberos not Kerberos wrapped in Negotiate
* Set `KRB5_TRACE=/tmp/krb.log` and run your process and see if that log file contains more info as to what happened
* Run the same code on a Windows host and see if it's able to authenticate with Kerberos

**Comment by balalnx16** [comment]
Thanks for the prompt response.

The Hostnames didn't  have their reverse PTR records configured correctly.

**Comment by jborean93** [comment]
Awesome, glad you were able to figure it out.
